# Generated by Django 3.2.19 on 2023-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='', max_length=500, upload_to=''),
        ),
    ]
