# Generated by Django 3.2.19 on 2023-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='qualification',
            new_name='status',
        ),
    ]
