# Generated by Django 3.2.19 on 2023-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
